### Farm games with account
POST http://localhost:4000/farm/start
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yWFAxMkRQVk1MdkcxY08xdTRGOFdSd1RpUFgiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3MDQ3NTU5ODgsImlhdCI6MTcwNDc1NTkyOCwiaXNzIjoiaHR0cHM6Ly9sZWFkaW5nLWFudGVhdGVyLTcwLmNsZXJrLmFjY291bnRzLmRldiIsIm5iZiI6MTcwNDc1NTkxOCwic2lkIjoic2Vzc18yYWVMcXQ0djlLYXlLbFdadFFPR3JyVWtMYXMiLCJzdWIiOiJ1c2VyXzJYaENJd0dqaVBZREMzNWxJV0JwRjBPYXBrTiJ9.G4wJxH34CLJ9SConDjBZxMMZCahhNz2iQDe83yzRhFfOmWsCg40m0xFlo7g2CsV67cfXJlRzAkxK7pxalX-BkXufI2yyKmU6oM74GR9ySKPsNUdGz1PkpbPBJB6xfTYcm1UapUulos8mgCdQ5Tt5p3gyhEjd_HuadHtcpI-gzbxw8BAEo3GacP_N0icQAHlsrJ58itnax2xpK_5ZfUCRF0AoY0ZRpIU_VoOmwJV-AvYZQL1i79lKFIf80W-zUQ8_FtJhHynjf_tB_ejGfrexEuLX78yCZAqMkJ7A-hRq3VOtRCwwPp5IrLJjK_P-QvYxkxA2KDQ1dMR-Qnf26cRHqw

{
  "accountName": "yversale",
  "gamesID": [489520]
}

### Add steam account
POST http://localhost:4000/steam-accounts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yWFAxMkRQVk1MdkcxY08xdTRGOFdSd1RpUFgiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3MDQ3NTU5ODgsImlhdCI6MTcwNDc1NTkyOCwiaXNzIjoiaHR0cHM6Ly9sZWFkaW5nLWFudGVhdGVyLTcwLmNsZXJrLmFjY291bnRzLmRldiIsIm5iZiI6MTcwNDc1NTkxOCwic2lkIjoic2Vzc18yYWVMcXQ0djlLYXlLbFdadFFPR3JyVWtMYXMiLCJzdWIiOiJ1c2VyXzJYaENJd0dqaVBZREMzNWxJV0JwRjBPYXBrTiJ9.G4wJxH34CLJ9SConDjBZxMMZCahhNz2iQDe83yzRhFfOmWsCg40m0xFlo7g2CsV67cfXJlRzAkxK7pxalX-BkXufI2yyKmU6oM74GR9ySKPsNUdGz1PkpbPBJB6xfTYcm1UapUulos8mgCdQ5Tt5p3gyhEjd_HuadHtcpI-gzbxw8BAEo3GacP_N0icQAHlsrJ58itnax2xpK_5ZfUCRF0AoY0ZRpIU_VoOmwJV-AvYZQL1i79lKFIf80W-zUQ8_FtJhHynjf_tB_ejGfrexEuLX78yCZAqMkJ7A-hRq3VOtRCwwPp5IrLJjK_P-QvYxkxA2KDQ1dMR-Qnf26cRHqw

{
  "accountName": "yversale",
  "password": "@998vmarkis"
}

### Remove steam account
DELETE http://localhost:4000/steam-accounts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImtpZCI6Imluc18yWFAxMkRQVk1MdkcxY08xdTRGOFdSd1RpUFgiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAiLCJleHAiOjE3MDQ3NTU5ODgsImlhdCI6MTcwNDc1NTkyOCwiaXNzIjoiaHR0cHM6Ly9sZWFkaW5nLWFudGVhdGVyLTcwLmNsZXJrLmFjY291bnRzLmRldiIsIm5iZiI6MTcwNDc1NTkxOCwic2lkIjoic2Vzc18yYWVMcXQ0djlLYXlLbFdadFFPR3JyVWtMYXMiLCJzdWIiOiJ1c2VyXzJYaENJd0dqaVBZREMzNWxJV0JwRjBPYXBrTiJ9.G4wJxH34CLJ9SConDjBZxMMZCahhNz2iQDe83yzRhFfOmWsCg40m0xFlo7g2CsV67cfXJlRzAkxK7pxalX-BkXufI2yyKmU6oM74GR9ySKPsNUdGz1PkpbPBJB6xfTYcm1UapUulos8mgCdQ5Tt5p3gyhEjd_HuadHtcpI-gzbxw8BAEo3GacP_N0icQAHlsrJ58itnax2xpK_5ZfUCRF0AoY0ZRpIU_VoOmwJV-AvYZQL1i79lKFIf80W-zUQ8_FtJhHynjf_tB_ejGfrexEuLX78yCZAqMkJ7A-hRq3VOtRCwwPp5IrLJjK_P-QvYxkxA2KDQ1dMR-Qnf26cRHqw

{
  "steamAccountId": "637f6258-c996-4625-abd3-39f3ceb24103",
  "accountName": "yversale",
  "username": "vitormarkis"
}

### List farming accounts
GET http://localhost:4000/farming-users
