POST http://localhost:3309/farm/start
Content-Type: application/json

{
  "userId": "user_2XkAyXBLx5ugXjAVx9w8QJtAf9y"
}

###

POST http://localhost:3309/farm/stop
Content-Type: application/json

{
  "userId": "user_2XkAyXBLx5ugXjAVx9w8QJtAf9y"
}

###

GET http://localhost:3309/farm/plan-status
Content-Type: application/json

{
  "userId": "user_2Xk8sUsugFULRFTZoMjprlpeu0t"
}
