POST http://localhost:4000/farm/start
Content-Type: application/json

{
  "userId": "user_2XhCIwGjiPYDC35lIWBpF0OapkN",
  "gamesID": [601510]
}

###

POST http://localhost:4000/farm/stop
Content-Type: application/json

{
  "userId": "user_2XhCIwGjiPYDC35lIWBpF0OapkN"
}

###

GET http://localhost:4000/farm/plan-status
Content-Type: application/json

{
  "userId": "user_2XhCIwGjiPYDC35lIWBpF0OapkN"
}

###

GET http://localhost:4000/up

###

POST http://localhost:4000/add-account
Content-Type: application/json

{
  "userId": "user_2XhCIwGjiPYDC35lIWBpF0OapkN",
  "username": "vitormarkis",
  "accountName": "yversale",
  "password": "@998vmarkis"
}

###

POST http://localhost:4000/code
Content-Type: application/json

{
  "code": "73GP2",
  "userId": "user_2XhCIwGjiPYDC35lIWBpF0OapkN",
  "accountName": "yversale"
}

###

POST http://localhost:4000/set-farming-games
Content-Type: application/json

{
  "userId": "user_2XhCIwGjiPYDC35lIWBpF0OapkN",
  "gamesID": [601510]
}

###

GET http://localhost:4000/list


